import '../model/movies.dart';

var content =
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.';

List<Movie> getMovies() {
  return [
    Movie(
      id: '9',
      name: 'Angry Birds',
      censorRating: 'R',
      synopsis: content,
      image: 'lib/assets/images/angrybirds.jpg',
      genre: ['CRIME', 'MYSTERY', 'DRAMA'],
      rating: 4.5,
      releaseDate: DateTime.now(),
      duration: Duration(hours: 2, minutes: 3),
      criticsCount: 10,
      userCount: 2432,
    ),
    Movie(
      id: '18',
      name: 'Avengers Infinity War',
      censorRating: 'R',
      synopsis: content,
      image: 'lib/assets/images/avengers.jpg',
      genre: ['Action', 'Horror'],
      rating: 3.9,
      releaseDate: DateTime.now(),
      duration: Duration(hours: 2, minutes: 13),
      criticsCount: 8,
      userCount: 232,
    ),
    Movie(
      id: '1',
      name: 'Batman Vs. Superman',
      censorRating: 'R',
      synopsis: content,
      image: 'lib/assets/images/batmanvsuperman.jpg',
      genre: ['CRIME', 'MYSTERY', 'DRAMA'],
      rating: 4.0,
      releaseDate: DateTime.now(),
      duration: Duration(hours: 2, minutes: 3),
      criticsCount: 10,
      userCount: 2432,
    ),
    Movie(
      id: '2',
      name: 'Itachi With Crow',
      censorRating: 'R',
      synopsis: content,
      image: 'lib/assets/images/itachi_crow.jpg',
      genre: ['Action', 'Horror'],
      rating: 3.0,
      releaseDate: DateTime.now(),
      duration: Duration(hours: 3, minutes: 11),
      criticsCount: 4,
      userCount: 432,
    ),
    Movie(
      id: '3',
      name: 'Avengers 2012',
      censorRating: 'R',
      synopsis: content,
      image: 'lib/assets/images/avenger2012.jpg',
      genre: ['Action', 'Horror'],
      rating: 4.0,
      releaseDate: DateTime.now(),
      duration: Duration(hours: 2, minutes: 37),
      criticsCount: 6,
      userCount: 1562,
    ),
    Movie(
      id: '4',
      name: 'Kakashi Hatake',
      censorRating: 'R',
      synopsis: content,
      image: 'lib/assets/images/kakashi.jpg',
      genre: ['Action', 'Horror'],
      rating: 4.5,
      releaseDate: DateTime.now(),
      duration: Duration(hours: 2, minutes: 8),
      criticsCount: 12,
      userCount: 2653,
    ),
    Movie(
      id: '15',
      name: 'Despicable Me',
      censorRating: 'R',
      synopsis: content,
      image: 'lib/assets/images/despicableme.jpeg',
      genre: ['CRIME', 'MYSTERY', 'DRAMA'],
      rating: 4.0,
      releaseDate: DateTime.now(),
      duration: Duration(hours: 2, minutes: 3),
      criticsCount: 10,
      userCount: 2432,
    ),
    Movie(
      id: '5',
      name: 'Naruto',
      censorRating: 'R',
      synopsis: content,
      image: 'lib/assets/images/kid_naruto.jpg',
      genre: ['Action', 'Horror'],
      rating: 3.4,
      releaseDate: DateTime.now(),
      duration: Duration(hours: 1, minutes: 57),
      criticsCount: 0,
      userCount: 32,
    ),
    Movie(
      id: '16',
      name: 'Despicable Me 3',
      censorRating: 'R',
      synopsis: content,
      image: 'lib/assets/images/despicableme3page.jpg',
      genre: ['Action', 'Horror'],
      rating: 3.9,
      releaseDate: DateTime.now(),
      duration: Duration(hours: 2, minutes: 13),
      criticsCount: 8,
      userCount: 232,
    ),
    Movie(
      id: '6',
      name: 'Pain',
      censorRating: 'R',
      synopsis: content,
      image: 'lib/assets/images/pain.jpg',
      genre: ['Action', 'Horror'],
      rating: 4.5,
      releaseDate: DateTime.now(),
      duration: Duration(hours: 2, minutes: 13),
      criticsCount: 8,
      userCount: 232,
    ),
    Movie(
      id: '17',
      name: 'Batman',
      censorRating: 'R',
      synopsis: content,
      image: 'lib/assets/images/batman.jpg',
      genre: ['Action', 'Horror'],
      rating: 3.9,
      releaseDate: DateTime.now(),
      duration: Duration(hours: 2, minutes: 13),
      criticsCount: 8,
      userCount: 232,
    ),
    Movie(
      id: '7',
      name: 'Despicable Me 2',
      censorRating: 'R',
      synopsis: content,
      image: 'lib/assets/images/despicableme2.jpg',
      genre: ['Action', 'Horror'],
      rating: 3.5,
      releaseDate: DateTime.now(),
      duration: Duration(hours: 2, minutes: 37),
      criticsCount: 6,
      userCount: 243,
    ),
    Movie(
      id: '11',
      name: 'Angry Birds 2',
      censorRating: 'R',
      synopsis: content,
      image: 'lib/assets/images/angrybirdspage.jpg',
      genre: ['CRIME', 'MYSTERY', 'DRAMA'],
      rating: 4.0,
      releaseDate: DateTime.now(),
      duration: Duration(hours: 2, minutes: 3),
      criticsCount: 10,
      userCount: 2432,
    ),
    Movie(
      id: '8',
      name: 'Uchiha Brothers',
      censorRating: 'R',
      synopsis: content,
      image: 'lib/assets/images/uchiha_bros.jpg',
      genre: ['Action', 'Horror'],
      rating: 5.0,
      releaseDate: DateTime.now(),
      duration: Duration(hours: 3, minutes: 7),
      criticsCount: 11,
      userCount: 2732,
    ),
    Movie(
      id: '10',
      name: 'Angry Birds 2',
      censorRating: 'R',
      synopsis: content,
      image: 'lib/assets/images/angrybirds2.jpeg',
      genre: ['CRIME', 'MYSTERY', 'DRAMA'],
      rating: 4.5,
      releaseDate: DateTime.now(),
      duration: Duration(hours: 2, minutes: 3),
      criticsCount: 10,
      userCount: 2432,
    ),
  ];
}
